Add install-min option to install-deps.sh
yairdar/devpod pull request #12
Opened 2022-08-18 10:48 UTC by djfedos

2022-08-18 14:05 UTC, yairdardev requested changes

2022-08-18 14:05 UTC, yairdardev commented on README.md
> +bash devpod/install-deps.sh install-min
install base tool and futher custom installation

2022-08-18 14:05 UTC, yairdardev commented on README.md
> +bash devpod/install-deps.sh install-all
setup-base

2022-08-18 14:05 UTC, yairdardev commented on src/devpod/install-deps.sh
> +if [[ ("$1" != "install-all") && ("$1" != "install-min") ]]; then
setup-base

2022-08-18 14:05 UTC, yairdardev commented on src/devpod/install-deps.sh
> +    echo "Usage: install-deps.sh install-all            will install all tools"
Usage: install-deps.sh setup-base     will install base minimal tools for futher installs

2022-08-18 14:05 UTC, yairdardev commented on src/devpod/install-deps.sh
> +    echo "Usage: install-deps.sh install-min            will install deps, zsh and oh-my-zsh"
Usage: `./install-deps.sh setup-base setup-os-conda setup-os-docker -p`
will install base minimal tools for futher installs

2022-08-18 14:05 UTC, yairdardev commented on src/devpod/install-deps.sh
> +    if [[ "$1" = "install-all" ]]; then
```
task setup-zsh-tools
if [[ "$2" != "" ]]; then
  shift
  task $@
```

2022-08-18 14:05 UTC, yairdardev commented on README.md
> +bash devpod/install-deps.sh install-all
another example `bash ./devpod/install-deps.sh setup-base setup-os-docker`

2022-08-20 15:35 UTC, djfedos commented on README.md
> +bash devpod/install-deps.sh install-all
Add `setup-base` and `setup-base args`
Add tests for both variations

2022-08-20 15:35 UTC, djfedos commented on src/devpod/install-deps.sh
> +    echo "Usage: install-deps.sh install-min            will install deps, zsh and oh-my-zsh"
Added

2022-08-20 15:36 UTC, djfedos commented on src/devpod/install-deps.sh
> +    echo "Usage: install-deps.sh install-all            will install all tools"
Added

2022-08-20 15:36 UTC, djfedos commented on src/devpod/install-deps.sh
> +    if [[ "$1" = "install-all" ]]; then
it works

2022-08-29 15:52 UTC, merged